BUG/MINOR: Makefile: fix compile error with USE_LUA=1 in ubuntu16.04
include/types/hlua.h:6:17: fatal error: lua.h: No such file or directory

(cherry picked from commit b286fffa4281860ed606a5f18b6994748afa09b3)
Signed-off-by: William Lallemand <wlallemand@haproxy.org>
(cherry picked from commit e0467825ca3c2131b1bdcccdba88f776d8fa259f)

Signed-off-by: Willy Tarreau <w@1wt.eu>